### ISSUE TITLE
List all mini-surveys required to be printed

### ISSUE THREAD

**Issue by goatchurchprime** [CaveSurveying/CUCCexposurveyissues#1]
Previous years minisurveys are here: http://expo.survex.com/expofiles/surveys/minisurveys2017/
and here:  http://expo.survex.com/expofiles/surveys/minisurveys2014/

Please post places that you would like to have done and to what scale

**Comment by BeckaLawson** [comment]
Deadline for printing by Becka: 4th July

**Comment by wobrotson** [comment]
- [ ] GSH and Fisch Gesicht, both small enough to print full surveys. I am currently drawing these up.
- [ ] Claytons Cock-Up: how to get there (see logbook entry from fleur , 2015), and the lead itself.
- [ ] Champagne on Ice: Grike Expectations and What Would Your Mother Say area.
- [ ] Sloppy Seconds: Second Wind area
- [ ] Northern Slackers: Beckoning Silence, Slackers5
- [ ] Anthemusa

**Comment by goatchurchprime** [comment]
From Anthony

- [x] All the deep Tunnocks stuff (everything in orange). Either cut it up into as many A4 sheets as makes sense or just make the whole lot at a high enough resolution that we can cut it up and scale it ourselves.
- [ ] String Fellows - Clayton's Cockup area
- [x] Bottom of Hiltaplenty in Balkonhöhle - all the blue and purple stuff at the eastern extremity of the survey.
- [x] Grey out Galactica since it is bloody huge and there are no leads. The colouring seems a bit arbitrary in this area, so maybe that could be reviewed at the same time.

**Comment by goatchurchprime** [comment]
this is out of date
