### ISSUE TITLE
Updating http://expo.survex.com/expofiles/surveyscans/2017/

### ISSUE THREAD

**Issue by BeckaLawson** [CaveSurveying/CUCCexposurveyissues#11]
This isn't refreshing so new files that have been added aren't appearing eg
http://expo.survex.com/expofiles/surveyscans/2017/2017%2338/index.html
should have drawn up surveys on.

How can I check the actual state of the survey scans without using rsync (I'm using a Windows laptop and rsync won't easily work)

**Comment by wookey** [comment]
log on to the server (as expo) and run 'python make.py' in the relevant expofiles/surveyscans/<year> directory (from 2014 on)

**Comment by BeckaLawson** [comment]
You need python installed, then run python make.py using putty or ssh when you are in the relevant directory (expofiles/surveyscans/2017 normally).

**Comment by goatchurchprime** [comment]
This also should rolled into #15 (the wiki cheatsheet)
