### ISSUE TITLE
List of areas of cave needing resurveying on 2018 Expo

### ISSUE THREAD

**Issue by wobrotson** [CaveSurveying/CUCCexposurveyissues#14]
In addition to the QM list, it would be good to have a list of areas of cave that need resurveying so that these can get  ticked off easily. Another good thing for new people to do under supervision of a sensible surveyer needing a rest day.

**Comment by BeckaLawson** [comment]
Here's the list (edit it to add)
#29 - 2017_cucc_24 gsoh - in Happy Butterfly / GSH
#30 - 2017#30 2017_cucc_24 Rift Piece - in Happy Butterfly / GSH
#39 (listed as #201439), Balkonhoelhe Nothing To See
#47 Nature Calls, Balkonhoehle Cathedral Chasm, Ash dropped the Mashterpiece and this has not been tied in along with rachel and george's continuation.
Mess with connection of Grike of the Earth / Loser Lido

**Comment by goatchurchprime** [comment]
no longer valid
