### ISSUE TITLE
Rerender Tunnocks and Balc A0 survey posters

### ISSUE THREAD

**Issue by goatchurchprime** [CaveSurveying/CUCCexposurveyissues#27]
v2 has been done.  v3 to have more labels and a few colour changes (have been amended to a poster version)

**Comment by goatchurchprime** [comment]
Fixes to be found here:
http://expo.survex.com/expofiles/surveys/264/2018/
and here:
http://expo.survex.com/expofiles/surveys/258/
the v3 ones

**Comment by BeckaLawson** [comment]
Being printed now
