### ISSUE TITLE
Missing surveys

### ISSUE THREAD

**Issue by goatchurchprime** [CaveSurveying/CUCCexposurveyissues#30]
Just updated the loser data

aven 1623-and-1626-no-schoenberg-hs.svx

Survex 1.2.33
Copyright © 1990-2017 Olly Betts
In file included from 1623-and-1626-no-schoenberg-hs.svx:1:
In file included from kataster/1623.svx:29:
In file included from kataster/../caves-1623/caves-smk.svx:17:
In file included from kataster/../caves-1623/caves-smk-north.svx:11:
kataster/../caves-1623/264/264.svx:474:10: error: Couldn’t open file “mudslope2”
 *include mudslope2
kataster/../caves-1623/264/264.svx:477:10: error: Couldn’t open file “mongolrally”
 *include mongolrally
kataster/../caves-1623/264/264.svx:480:10: error: Couldn’t open file “littleboy”
 *include littleboy
kataster/../caves-1623/264/264.svx:483:10: error: Couldn’t open file “floodland”
 *include floodland
Removing trailing traverses...

**Comment by pwithnall** [comment]
@georgebreley, paperless surveying doesn’t mean you can get away without running `hg add` on new files before you commit and push.

**Comment by pwithnall** [comment]
Resolved by @georgebreley in changeset 1770:091de6ec6ea6.
