### ISSUE TITLE
Get all components of survey data working on [George's]/anyone's machine

### ISSUE THREAD

**Issue by goatchurchprime** [CaveSurveying/CUCCexposurveyissues#4]
Need to download survey data, tunnel data, scans and make survex and tunnel able to run

Ask questions here

**Comment by goatchurchprime** [comment]
Get expo loser data:  Download and run TortoiseHG
Clone (or update) from the repository.  
If you are using a mac you might have to do it with the command line, and then open it in the workbench
 > hg clone ssh://expo@expo.survex.com/loser

Do the same with tunneldata repository (which is also mercurial type).

Now you need to copy out the surveyscans, which are a vast set of binary files.  First get the directory structure of the scans for all the years by getting a command window open in the directory containing the tunneldata directory and typing:

> rsync -av -f"+ */" -f"- *" expo@expo.survex.com:expofiles/surveyscans .

Now you can selectively download by year, like this:

> rsync -av expo@expo.survex.com:expofiles/surveyscans/2017/ surveyscans/2017/

Now you should be able to run tunnel and look at your data

(If you get a background image not loading, check the full file name for it; in case it starts with "expofiles/surveyscans" and delete the "expofiles" part of the file path)

**Comment by wobrotson** [comment]
how do I put an updated svx file onto the repository?

**Comment by goatchurchprime** [comment]
You need to have installed mercurial (hg).  It has a UI for windows known as TortoiseHG.  Look for TortoiseHG workbench and use that to see the files and all their history.  Ask becka for details 

One command line:
hg pull
hg update
hg add yourfile.xml
hg commit -uyourname

[ this throws you into VI.  Hit "i" then type your comment.  Then do <Escape> and ":wq" then return to save and quit.  There are help videos and pages for VI editor https://www.howtogeek.com/102468/a-beginners-guide-to-editing-text-files-with-vi/ ]

hg push

**Comment by goatchurchprime** [comment]
You can add files in and do it the other direction like so:
   rsync -av surveyscans/2017/ expo@expo.survex.com:expofiles/surveyscans/2017/ 

(It's completely futile trying to get rsync to work on windows, I've found.  Best to run these commands under a unix operating system and copy across using an SD card.)

**Comment by goatchurchprime** [comment]
Bugs for tunnel can be posted here:  https://bitbucket.org/goatchurch/tunnelx/issues?status=new&status=open

**Comment by goatchurchprime** [comment]
Will move this into wiki
