### ISSUE TITLE
2017-cucc-24 GSH Happy Butterfly / 2017-cucc-28 Fisch Gesicht / 

### ISSUE THREAD

**Issue by BeckaLawson** [CaveSurveying/CUCCexposurveyissues#7]
- [x] GPS available
- [x] length and depth stats ready
- [ ] plan survey complete
- [ ] description complete
- [ ] photos complete
- [ ] reported to Robert Seebacher for Kataster
- [ ] added as new cave with all above info to expo website
- [ ] re-tag with final tag

**Comment by BeckaLawson** [comment]
Started in Tunnel but some poor drawings so unfinished (needs some sections resurveying in 2018)

**Comment by wobrotson** [comment]
which bits need resurveying? I will scan in the bit I have just drawn now, wallet 50. 12 monkeys, fish face

**Comment by BeckaLawson** [comment]
This is what I think needs drawing up or resurveying

http://expo.survex.com/expofiles/surveyscans/2017/

#28 The notes there are mostly for something else and the correct notes are missing *except*  for notes3 on the left side
#29 As for #28, the correct notes are missing and the ones there are the wrong ones
#30 Dreadful notes by Luke - no elevation and terrible plan. I didn't think I could even attempt drawing these up
#46 I'm not sure this data has been tied in to the main survex file and these may be the wrong notes

Whoever has access to the actual folder of paper surveys (Wookey?) is probably the best person to check these issues out. I told Wookey about them in the autumn so he may already have done this.

**Comment by wobrotson** [comment]
looks like the drawing for #27 is incomplete as well, I'll do that next

**Comment by wobrotson** [comment]
[scan_plan_12monkeys2017_28.pdf](https://github.com/CaveSurveyGIS/CUCCexposurveyissues/files/2108257/scan_plan_12monkeys2017_28.pdf)

**Comment by wobrotson** [comment]
folder #26: numeric data is correct but vector data is missing, what is there is an incorrect drawing. have looked for the correct drawing in neighbouring files but it appears missing.

**Comment by wobrotson** [comment]
wallets 24 and 34 appear to be duplicates.

**Comment by wobrotson** [comment]
about to embark on CUCC2017-21-22, wallets #24 and #34

**Comment by wobrotson** [comment]
![scan_plan_cucc-2017-22](https://user-images.githubusercontent.com/40319079/41501117-02aa6a92-7196-11e8-9a07-256696aa19db.jpg)

**Comment by wobrotson** [comment]
plan for wallet #27 drawn up on paper and scanned in. Tunnelling to be done.

**Comment by goatchurchprime** [comment]
In fishface work to be done:

backgrounds in position ready to tunnelize: icytube, canyon, fishface1, 12monkeys, 
missing: toto_to_crystalcrumble not in wallet 2018#19, and entrance totally missing

**Comment by goatchurchprime** [comment]
duplicate now
