### ISSUE TITLE
Balkonhoehle - Sloppy Seconds

### ISSUE THREAD

**Issue by wobrotson** [CaveSurveying/CUCCexposurveyissues#9]
about to draw up wallet 42 dog end series for sloppy seconds and scan in.

**Comment by wobrotson** [comment]
just fixed some issues in the data input for the dog end series survex file, will upload the updated version

**Comment by BeckaLawson** [comment]
OK ... I already tried to draw up some of this I think so check if that is affected by changing the survex file

**Comment by wobrotson** [comment]
it will be affected. I am about to draw up the corrected version.

**Comment by wobrotson** [comment]
![scan_plan_dogendseries_264](https://user-images.githubusercontent.com/40319079/41500573-2f3eec68-718c-11e8-878c-e7b2ebadf3c7.jpg)

**Comment by BeckaLawson** [comment]
George can hopefully commit this dogend drawing once he's finished slaying the Beast

**Comment by BeckaLawson** [comment]
Now committed
